export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA'

export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA'

export const FAILED_SEARCH_DATA = 'FAILED_SEARCH_DATA'

export const RESET_SEARCH_DATA = 'RESET_SEARCH_DATA'

export const REQUEST_DETAIL_DATA = 'REQUEST_DETAIL_DATA'

export const RECEIVE_DETAIL_DATA = 'RECEIVE_DETAIL_DATA'

export const FAILED_DETAIL_DATA = 'FAILED_DETAIL_DATA'